baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Markus Portfolio'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  showPoweredBy = false
  customCSS = ["css/custom.css"]
  showCopyright = false